language: node_js
node_js:
- 6.11.1

branches:
  only:
  - master

before_install:
- git config --global user.email "travis-ci@legalthings.net"
- git config --global user.name "Travis CI"
- git fetch origin 'refs/tags/*:refs/tags/*'

after_success:
- npm install mversion -g
- test "$TRAVIS_BRANCH" != 'master' -o "$TRAVIS_PULL_REQUEST" != "false" || test -n "$(git tag --contains)" || .bin/bump-version

deploy:
  provider: npm
  email: sven.stam@gmail.com
  api_key:
    secure: Skq2HUhXg0yOofS7G6XB1n7bcM+0R/hHO7t2t9CcmRE2g0tKPpQ8rrvnGyuH1q9+hMbfVJrMtqqYtgOBgMnjXdAFbfMmoCvIdwwFweqH5Mr7VzyUU13cRlGXF1GQmS8mkIYW2cw7rF6v72S+Pbv9NcEcmsllrxQe4LhupSMpIClABr9QLWQOhALzfqouhDwPwdjncCbDmPWmTu7dVOyp+ON7tFwf5qEfn0Z+It4w0Nb/H0aofoLsFbtE34lq0aoLtzkce0saGrhwK+WnXdSiAbOI/JLD32QCzY5d2CcOulOZYIdTf00NNfRUs8ANiKlnvC4OyLv7pbQHJeF77QszR/dvfngqYmh+kXy0On28rjKcORvodLq5GQsM7hLFiCeL/DLe85VG9dTRcnLbAak06njDROaN1Yy30Euj+DrPT394kbj90DtTeJF8sJfGu37jihvAttdybggR0K971Xfy0HIaJsJtEmtnCiQVwgBo9VyescFE/ZF91kneKa+GibwsIkon/q4CT1eftI2CqUBr+rv/xRiLpunOOj6g7wZLyaxw6YcNkDIk57khYsYPQ8FRnhs6aKYT4WoojQPLw9A89KC/BUm7VnZbmSBOdBdJuEKWGp1UUw3Z4PfWHvLQY5ZsyVwE5L7J+wz3p5ugJZ8IXLbkklOXBmil2H8LRZK/P94=
  on:
    branch: master
