language: node_js
node_js:
- 6.11.1
- 8.1.4

branches:
  only:
  - master

before_install:
- git config --global user.email "travis-ci@legalthings.net"
- git config --global user.name "Travis CI"
- git fetch origin 'refs/tags/*:refs/tags/*'

after_success:
- npm install mversion -g
- test "$TRAVIS_BRANCH" != 'master' -o "$TRAVIS_PULL_REQUEST" != "false" || test -n "$(git tag --contains)" || bin/bump-version

deploy:
  provider: npm
  email: sven.stam@gmail.com
  api_key:
    secure: JvXPHHAVbvH4oE+pmCXSm/tV3qYqLJHcBK0dNI01bh+OHzSjFMgY7VNUjsJQhInsONTkYk5s0YbVTJH1pBJ739NGNqcUL88s9ytRliRFjJFQwX11xx/4C0UFBpd58vKwYhH2QS6JM6Rnen0bx5ptLhCIwpgNs+yGABfvae5i1HnnhXpnYj6GrpZrkjdrz6SgM1L8379tdLx8wfO3AY2+oV+WwLr3mQEvbjwaNMSFxAsQU9OQy8c4NQT+v/6wOqRMHEIUvAtLKB8RUJT4opvZxAapd6fpWxW6m6oWlD5ffc3yJWK6FYp5PmkPVpmm6yB7ihnx9TCgvdV9GFn/VrI3X282SprFz3Jo0x+THdyEjMO4zjB2YL7vlYcEj9T6ilPk40R+nWjCuY0k9fllfroGMNlaUth4limOsKDYywjpt5MP0IBuOBRKZdLKs/+HoKJRnZJgEmkZLtBU4HDQReXKKp/0D9hMFmgmX0rRJt7X8WEfD2TFJgcrIyRzePsulhEatiO330ZUXzDTILg/BvIMI8J55+4DhVqeRgK0gZiqZ8zbUww4MqP8xP2X9Ezb57L7Oh9S3mwQs7ygJEhFXn4Ot/gmRPuQjW+9GQzdFksjExY5d+3ocCda22dqzYPf7I4Sg/Bq4+JAAXgiQYb+UHB2HNLK9IbDyaX3HobOdJRXkV8=
  on:
    branch: master
